DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS authors;

CREATE TABLE authors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    birth_year  INT
);

CREATE TABLE books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author_id BIGINT NOT NULL,
    "year" INT NOT NULL,
    genre VARCHAR(255) NOT NULL,
    CONSTRAINT fk_books_author FOREIGN KEY (author_id) REFERENCES authors(id)
);

INSERT INTO authors(first_name, last_name, birth_year) VALUES
 ('George', 'Orwell', 1903),
 ('Joanne', 'Rowling', 1965);

INSERT INTO books(title, author_id, "year", genre)
VALUES
  ('1984', 1, 1949, 'Dystopian'),
  ('Harry Potter and the Philosopher''s Stone', 2, 1997, 'Fantasy');
